#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : intel-cmt-cat
Version  : 0.1.3
Release  : 1
URL      : https://github.com/01org/intel-cmt-cat/archive/v0.1.3.tar.gz
Source0  : https://github.com/01org/intel-cmt-cat/archive/v0.1.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: intel-cmt-cat-bin
Patch1: 0001-Add-install-rule-and-instructions.patch

%description
========================================================================
April 2015
========================================================================

%package bin
Summary: bin components for the intel-cmt-cat package.
Group: Binaries

%description bin
bin components for the intel-cmt-cat package.


%prep
%setup -q -n intel-cmt-cat-0.1.3
%patch1 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install PREFIX=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/bin/pqos
